-- =============================================================================
-- Hospital CRM — demo seed data (auto-generated by scripts/generate-seed.mjs)
-- Passwords are PBKDF2-HMAC-SHA256 hashes; see docs/SECURITY.md for the list.
-- =============================================================================
PRAGMA foreign_keys = ON;

INSERT OR IGNORE INTO departments (id, code, name, description, location, phone) VALUES
  (1, 'CARDIO', 'Кардиологическое отделение', 'Диагностика и лечение ССС', 'Корпус А, 3 этаж', '+7 495 000-10-01'),
  (2, 'NEURO',  'Неврологическое отделение',  'Заболевания нервной системы', 'Корпус А, 4 этаж', '+7 495 000-10-02'),
  (3, 'THERAPY','Терапевтическое отделение', 'Общая терапия и профилактика', 'Корпус Б, 1 этаж', '+7 495 000-10-03');

INSERT OR IGNORE INTO users (username, email, full_name, password_hash, password_salt, password_iterations, role_id, status) VALUES
  ('admin', 'admin@hospital.local', 'Системный администратор', 'RiMdlhpTcigrA/opqx73NcB21RBETSrrieTB1Pk5Gwc=', 'OFw4Uqhoc8ms5fvPaRKHkg==', 25000, 5, 'active'),
  ('chief', 'chief@hospital.local', 'Волков Андрей Петрович', 'Sp1VMLRaURtpYaM+C4xuXM+8CBXV2QUXIHz6fVFPnRE=', 'OXCtqIowfd/rTLINM+odqg==', 25000, 4, 'active'),
  ('head_card', 'head_card@hospital.local', 'Соколова Марина Ивановна', 'z/KZdLPO77z9lPgiBQkJaOiGzorWMIMnZawv3j0AWWE=', 'tTtTyGcUZWi3n41ogf7ZxA==', 25000, 3, 'active'),
  ('head_neuro', 'head_neuro@hospital.local', 'Морозов Игорь Викторович', 'ThxKbRRhov6ONbnnicEgZ8U4jFR5zVRZINNGxWMLdPI=', 'pk13XuOlGSX/3ELsRu3nVQ==', 25000, 3, 'active'),
  ('doctor1', 'doctor1@hospital.local', 'Петрова Елена Сергеевна', 'bxGRMtPDsjfh16zJqqZYrj48+e/MBMED2n1mdQf6OZ4=', 'UEw/scgvLBhWPClkbsbI+Q==', 25000, 2, 'active'),
  ('doctor2', 'doctor2@hospital.local', 'Никитин Павел Олегович', '9ddJDegN6MB/XwoOoil3MpGXRvh9Uj6GJzF4TKBNKf0=', 'Gv6UGWdoe2d8/PBlZPyJuA==', 25000, 2, 'active'),
  ('doctor3', 'doctor3@hospital.local', 'Кузнецов Дмитрий Андреевич', 'N6LqV6JeRuRrv2f7cl7V491WsmF6JgiBXCC/3q6id3Y=', 'pVpZwLH18Q9o9xObtHN+Bw==', 25000, 2, 'active'),
  ('patient1', 'patient1@hospital.local', 'Иванов Сергей Николаевич', 'cGJ9e/+SdeS1lN2pdRezEM3zu1Ye/1ygHQYVsPQyZU0=', 'oxhE8nN60uSk5LwVgsjCMQ==', 25000, 1, 'active'),
  ('patient2', 'patient2@hospital.local', 'Смирнова Ольга Дмитриевна', 'LslBl2HReH9pyYHX5Y5CzIPhKYwI3kIsGd2rkVLXxkU=', 'EOJD9iD+bS6HRGXj6V7bRQ==', 25000, 1, 'active'),
  ('patient3', 'patient3@hospital.local', 'Григорьев Артём Олегович', 'dibQyNHRIcvoBf54yozhE15Yec23XLpMi/e1Azuw5Sk=', 'SIsry8LAa6gy2fpfR2bDSQ==', 25000, 1, 'active');

UPDATE departments SET head_user_id = (SELECT id FROM users WHERE username='head_card')  WHERE code='CARDIO';
UPDATE departments SET head_user_id = (SELECT id FROM users WHERE username='head_neuro') WHERE code='NEURO';

INSERT OR IGNORE INTO doctors (id, user_id, department_id, specialty, category, room, cabinet_phone) VALUES
  (1, (SELECT id FROM users WHERE username='head_card'),  1, 'Кардиолог',   'высшая', '301', '+7 495 000-10-11'),
  (2, (SELECT id FROM users WHERE username='head_neuro'), 2, 'Невролог',    'высшая', '401', '+7 495 000-10-12'),
  (3, (SELECT id FROM users WHERE username='doctor1'),    1, 'Кардиолог',   'первая', '302', '+7 495 000-10-13'),
  (4, (SELECT id FROM users WHERE username='doctor2'),    3, 'Терапевт',    'первая', '101', '+7 495 000-10-14'),
  (5, (SELECT id FROM users WHERE username='doctor3'),    2, 'Невролог',    'вторая', '402', '+7 495 000-10-15');

INSERT OR IGNORE INTO patients (id, patient_no, user_id, full_name, gender, birth_date, phone, email, blood_type, status) VALUES
  (1, 'P-000001', (SELECT id FROM users WHERE username='patient1'), 'plain:Иванов Сергей Николаевич', 'male',   'plain:1985-04-12', 'plain:+7 916 111-22-33', 'plain:s.ivanov@example.com', 'A+',  'active'),
  (2, 'P-000002', (SELECT id FROM users WHERE username='patient2'), 'plain:Смирнова Ольга Дмитриевна', 'female', 'plain:1990-09-25', 'plain:+7 916 222-33-44', 'plain:o.smirnova@example.com','B-',  'active'),
  (3, 'P-000003', (SELECT id FROM users WHERE username='patient3'), 'plain:Григорьев Артём Олегович',  'male',   'plain:1978-01-30', 'plain:+7 916 333-44-55', 'plain:a.grigoriev@example.com','O+', 'active'),
  (4, 'P-000004', NULL,                                              'plain:Егорова Наталья Петровна',  'female', 'plain:1965-07-15', 'plain:+7 916 444-55-66', 'plain:n.egorova@example.com', 'AB+', 'active'),
  (5, 'P-000005', NULL,                                              'plain:Фёдоров Максим Ильич',      'male',   'plain:2001-11-03', 'plain:+7 916 555-66-77', 'plain:m.fedorov@example.com', 'A-',  'active');

INSERT OR IGNORE INTO appointments (patient_id, doctor_id, department_id, scheduled_at, duration_min, type, status) VALUES
  (1, 3, 1, datetime('now','-12 days'), 30, 'consultation', 'completed'),
  (1, 3, 1, datetime('now','-3 days'),  30, 'followup',     'completed'),
  (1, 3, 1, datetime('now','+4 days'),  30, 'followup',     'scheduled'),
  (2, 1, 1, datetime('now','-8 days'),  45, 'consultation', 'completed'),
  (2, 1, 1, datetime('now','+2 days'),  30, 'followup',     'confirmed'),
  (3, 5, 2, datetime('now','-5 days'),  30, 'consultation', 'completed'),
  (3, 5, 2, datetime('now','+7 days'),  30, 'followup',     'scheduled'),
  (4, 4, 3, datetime('now','-2 days'),  30, 'consultation', 'completed'),
  (4, 4, 3, datetime('now','+6 days'),  30, 'followup',     'scheduled'),
  (5, 4, 3, datetime('now','-1 days'),  30, 'consultation', 'no_show'),
  (5, 2, 2, datetime('now','+1 days'),  30, 'consultation', 'scheduled'),
  (2, 4, 3, datetime('now','-20 days'), 30, 'consultation', 'cancelled');

INSERT OR IGNORE INTO medical_records (patient_id, doctor_id, visit_date, complaints, diagnosis, icd_code, treatment, recommendation) VALUES
  (1, 3, datetime('now','-12 days'), 'plain:Боли в груди при нагрузке', 'plain:Стенокардия напряжения, ФК II', 'I20.8', 'plain:Бисопролол 5 мг/сут', 'plain:Контроль АД, повторный приём через 2 недели'),
  (1, 3, datetime('now','-3 days'),  'plain:Улучшение, боли реже',      'plain:Стенокардия напряжения, ФК I',  'I20.8', 'plain:Продолжить терапию', 'plain:ЭКГ-контроль через месяц'),
  (2, 1, datetime('now','-8 days'),  'plain:Перебои в работе сердца',   'plain:Пароксизмальная тахикардия',    'I47.1', 'plain:Метопролол 25 мг', 'plain:Холтер-ЭКГ'),
  (3, 5, datetime('now','-5 days'),  'plain:Головные боли, головокружение', 'plain:Вертеброгенная цервикалгия', 'M54.2', 'plain:НПВС курсом 7 дней', 'plain:МРТ ШОП'),
  (4, 4, datetime('now','-2 days'),  'plain:Повышенное АД до 160/95',   'plain:Артериальная гипертензия II ст.','I10', 'plain:Периндоприл 5 мг', 'plain:Дневник АД');

INSERT OR IGNORE INTO analyses (id, patient_id, doctor_id, type_id, ordered_at, performed_at, status) VALUES
  (1, 1, 3, (SELECT id FROM analysis_types WHERE code='CBC_HGB'), datetime('now','-12 days'), datetime('now','-11 days'), 'completed'),
  (2, 1, 3, (SELECT id FROM analysis_types WHERE code='BIO_CHOL'),datetime('now','-12 days'), datetime('now','-11 days'), 'completed'),
  (3, 1, 3, (SELECT id FROM analysis_types WHERE code='ECG'),     datetime('now','-3 days'),  datetime('now','-3 days'),  'completed'),
  (4, 2, 1, (SELECT id FROM analysis_types WHERE code='CBC_ESR'), datetime('now','-8 days'),  datetime('now','-7 days'),  'completed'),
  (5, 2, 1, (SELECT id FROM analysis_types WHERE code='TSH'),     datetime('now','-8 days'),  NULL,                        'in_progress'),
  (6, 3, 5, (SELECT id FROM analysis_types WHERE code='CXR'),     datetime('now','-5 days'),  datetime('now','-4 days'),  'completed'),
  (7, 4, 4, (SELECT id FROM analysis_types WHERE code='BIO_GLU'), datetime('now','-2 days'),  datetime('now','-1 days'),  'completed');

INSERT OR IGNORE INTO analysis_results (analysis_id, value_numeric, flag, comment) VALUES
  (1, 118, 'low',  'plain:Лёгкая анемия'),
  (2, 6.4, 'high', 'plain:Гиперхолестеринемия'),
  (3, NULL, NULL,  'plain:Ритм синусовый, ЧСС 72'),
  (4, 28,  'high', NULL),
  (6, NULL, NULL,  'plain:Очаговых изменений не выявлено'),
  (7, 5.2, 'normal', NULL);

